version: "3.8"

services:
    app:
        build: .
        command: sh -c "python main.py"
        image: exeller/cicd-starter:latest
        ports:
            - "80:8000"
        volumes:
            - ./src:/src
